version: "3"

services:
  golang:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./:/books_rest_app:Z
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data:Z
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    driver: bridge